using System;
using System.Collections.Generic;

#nullable disable

namespace PuzzlesoftApi.Model
{
    public partial class ClientDetails2
    {
        public string MedMemo { get; set; }
        public string MedProp { get; set; }
        public string HospitalTransfer { get; set; }
        public string DayarHtml { get; set; }
        public string PlaceHtml { get; set; }
        public string TtMedadimHtml { get; set; }
        public string MedadimHtml { get; set; }
        public string TbClientsiudyNew { get; set; }
        public string ClientsiudyNew { get; set; }
        public string OsekId { get; set; }
        public string Meaaged { get; set; }
        public string Company { get; set; }
        public string Idcard { get; set; }
        public short? MasavDay { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string MailBox { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public string Details { get; set; }
        public int Id { get; set; }
        public bool? Archive { get; set; }
        public string NameView { get; set; }
        public string Kind1 { get; set; }
        public short? MainKind { get; set; }
        public string Kind2 { get; set; }
        public string Toaar { get; set; }
        public string Sochen { get; set; }
        public bool? Maham { get; set; }
        public int? Kind1Id { get; set; }
        public int? Kind2Id { get; set; }
        public int? GoremMafneId { get; set; }
        public int? SochenId { get; set; }
        public string Kod { get; set; }
        public int? UserId { get; set; }
        public string Kupa { get; set; }
        public string EnglishName { get; set; }
        public DateTime? Birthday { get; set; }
        public string FatherName { get; set; }
        public string BirthCountry { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public int? Age { get; set; }
        public string Lang { get; set; }
        public short? Childs { get; set; }
        public string AliaYear { get; set; }
        public string Bituah { get; set; }
        public int? LastTnuahId { get; set; }
        public DateTime? LastTnuahDate { get; set; }
        public string Gender { get; set; }
        public DateTime? KabalaDate { get; set; }
        public bool? IsMasav { get; set; }
        public string NimanName { get; set; }
        public string NimanAddress { get; set; }
        public short? OptNiman { get; set; }
        public bool? NotCharged { get; set; }
        public string LastTnuah { get; set; }
        public bool? IsMabar { get; set; }
        public bool? AutoMirsham { get; set; }
        public string Bank { get; set; }
        public string Snif { get; set; }
        public string Account { get; set; }
        public string MyListUsers { get; set; }
        public string DayarPhone { get; set; }
        public int? Interkum { get; set; }
        public short? Mahoz { get; set; }
        public int? TekenMita { get; set; }
        public short? BedNum { get; set; }
        public short? RoomId { get; set; }
        public string AgafName { get; set; }
        public short? AgafId { get; set; }
        public string RoomName { get; set; }
        public string DiurKind { get; set; }
        public int? DiurKindId { get; set; }
        public int? Idnum { get; set; }
        public string Properties { get; set; }
        public short? MahlakaId { get; set; }
        public string Mahlaka { get; set; }
        public short? SponserId { get; set; }
        public byte? MahlakaIdold { get; set; }
        public decimal? PriceEnter { get; set; }
        public decimal? PriceBack { get; set; }
        public DateTime? DateNeedEnter { get; set; }
        public int? RelatedClient { get; set; }
        public short? LocationId { get; set; }
        public DateTime? DateFirst { get; set; }
        public string MarketingRoom { get; set; }
        public string MarketingAgaf { get; set; }
        public short? TifkudStatusId { get; set; }
        public short? MahlakaKindId { get; set; }
        public string TifkudStatus { get; set; }
        public DateTime? LastTnuahDate2 { get; set; }
        public int? CityId { get; set; }
        public int? RoomIdold { get; set; }
        public int? BirthMonth { get; set; }
        public short? BedNumOld { get; set; }
        public string CarNum { get; set; }
        public short? MarketingTifkudStatusId { get; set; }
        public DateTime? DateAsk { get; set; }
        public int? TnuahId { get; set; }
        public int? MasavIdCard { get; set; }
        public int? SponserIdold { get; set; }
        public string Sponser { get; set; }
        public string GoremMafne { get; set; }
        public string FamilyStatus { get; set; }
        public short? LeaveKindId { get; set; }
        public string CarDetails { get; set; }
        public string RoomClass { get; set; }
        public string NameViewZug { get; set; }
        public string CarNumZug { get; set; }
        public string CarDetailsZug { get; set; }
        public string Phone1Zug { get; set; }
        public short? BankId { get; set; }
        public string Job { get; set; }
        public int? InviteKind { get; set; }
        public string TnuahDetails { get; set; }
        public string Phone3 { get; set; }
        public string KodHilut { get; set; }
        public string BmwebUserName { get; set; }
        public string BmwebPassword { get; set; }
        public string Languages { get; set; }
        public string RelatedNameIdcard { get; set; }
        public DateTime? RelatedNameBday { get; set; }
        public string RelatedNameWorkJob { get; set; }
        public string RelatedNameBcountry { get; set; }
        public string ArmyLevel { get; set; }
        public string ArmyId { get; set; }
        public string RelatedName { get; set; }
        public string UserPassport { get; set; }
        public string MedicalGroup { get; set; }
        public string CurrentStatus { get; set; }
        public string ArrivedFrom { get; set; }
        public string MarketingTifkudStatus { get; set; }
        public string Hospital { get; set; }
        public DateTime? RelatedWorkerBday { get; set; }
        public DateTime? WorkerJobStart { get; set; }
        public DateTime? WorkerJobEnd { get; set; }
        public string RelatedWorkerBcountry { get; set; }
        public short? WorkerJobPer { get; set; }
        public string BmwebKupa { get; set; }
        public string KupaSnif { get; set; }
        public int? KupaSnifId { get; set; }
        public short? KupaId { get; set; }
        public string WorkerUserName { get; set; }
        public string Profile1 { get; set; }
        public string MahozName { get; set; }
    }
}
